import type { Metadata } from "next";
import "./fanta.css";

export const metadata: Metadata = {
  title: "MDNOTES | Easy Notes Taking",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div id="app"> {children}</div>
        <div id="portal"></div>
      </body>
    </html>
  );
}
